### ISSUE TITLE
Working config should generate list of data products from wildcard in `read:`

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#137]
When I try to call `run --ci` on a config.yaml with a read block:
```
read:
- data_product: data_product/read/*
```
The entire block seems to be missing from the working config.

Note that I have `data_product/read/1` and `data_product/read/1/2` in my local registry.

**Comment by jwscook** [comment]
@richardreeve is there a list of implementation priorities anywhere?

**Comment by jwscook** [comment]
After marking & Christmas @richardreeve to write down logic of this here so that @kzscisoft can integrate into the current architecture.

**Comment by kzscisoft** [comment]
See test https://github.com/FAIRDataPipeline/FAIR-CLI/blob/73d600e62b2747a602d0d5adb7878c4a8c4ae998/tests/test_user_config.py#L87

This uses the example registry data to construct a scenario using the template `config.yaml`:
```yaml
run_metadata:
  default_input_namespace: <NAMESPACE>
  description: <NAMESPACE> wildcards testing
read:
- data_product: <WILDCARD-PATH>
```
