### ISSUE TITLE
Wildcards broken in write block

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#140]
When attempting to generate a working config from the following write block:
```
write:
- data_product: data_product/write/wildcard/b873cb1e1a51f1b8c9306c35b4d34cb08b82526f/*
  description: A csv file
  file_type: csv
  use:
    version: ${{MAJOR}}
```

A working config is generated without a write block and the following warning is returned:
```
WARNING:FAIRDataPipeline.ConfigYAML:Missing use:data_product in {'data_product': 'data_product/write/wildcard/b873cb1e1a51f1b8c9306c35b4d34cb08b82526f/1/2', 'description': 'A csv file', 'file_type': 'csv', 'use': {'namespace': 'testing', 'version': '${{MAJOR}}'}, 'public': True}
WARNING:FAIRDataPipeline.ConfigYAML:Missing use:data_product in {'data_product': 'data_product/write/wildcard/b873cb1e1a51f1b8c9306c35b4d34cb08b82526f/1', 'description': 'A csv file', 'file_type': 'csv', 'use': {'namespace': 'testing', 'version': '${{MAJOR}}'}, 'public': True}
```
