### ISSUE TITLE
fair run ignores version out of use block

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#27]
`fair run` does not take version info when not in a use block. It should accept version in or out of a use block in a write statement.

**Comment by DennisReddyhoff** [comment]
@richardreeve 

So both:

```
write:
- data_product: test/array
  description: test array with simple data
  use:    
    version: 0.1.0
```

and

```
write:
- data_product: test/array
  description: test array with simple data 
  version: 0.1.0
```

should be valid?
