### ISSUE TITLE
`fair run` doesn't process wild cards correctly

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#29]
Config file write block:

```yaml
write:
- data_product: test/*
  description: test csv file with simple data
  file_type: csv
  use:
    version: ${{ PATCH }}
```

returns:
```
Warning: Failed to retrieve object of type 'd/a/t/a/_/p/r/o/d/u/c/t' using method 'get' and arguments:
	url = https://data.scrc.uk/api/data_product/?name=test/*
```

**Comment by DennisReddyhoff** [comment]
This is for me thinking out loud:

Warning is because of a 403 error, the strange looking object type is due to the join method being used incorrectly. Actual problem is that the get method is trying to use the remote registry and not local

**Comment by DennisReddyhoff** [comment]
#33 

@soniamitchell Fix should now be in place under dev-wildcards branch, can you retest with the same write block and let me know what happens?

**Comment by soniamitchell** [comment]
```yaml
write:
- data_product: test/csv*
  description: aljf
```
returns:
```yaml
write:
- data_product: test/csv*
  description: aljf
  use:
    version: 0.0.3
- data_product: test/csv
  description: aljf
  use:
    version: 0.0.3
```
but should return version 0.0.1 for test/csv* since patch is default

**Comment by soniamitchell** [comment]
Are we including the read block in this issue? If so,  
```yaml
read:
- data_product: test/csv*
```
returns:
```yaml
read:
- data_product: test/csv*
- data_product: test/csv
```
but should include version numbers
