### ISSUE TITLE
Allow FAIR-CLI to test against a fake remote repo in CI 

### ISSUE THREAD

**Issue by soniamitchell** [FAIRDataPipeline/FAIR-CLI#52]
As well as the existing:
```yaml
local:
    data_store: /home/runner/.fair/data/
    directory: /home/runner/.fair/registry/
    uri: http://localhost:8000/api/
  origin:
    data_store: https://data.scrc.uk/data/
    token: ${{ github.workspace }}/token.txt
    uri: https://data.scrc.uk/api/
```
we might also have a remote option for testing on GH
```yaml
  remote:
    data_store: /home/runner/.fair/remote_data/
    directory: /home/runner/.fair/remote_registry/
    uri: http://localhost:8001/api/
```
That is, if `origin` isn't in the file, the CLI would check for `remote`
