### ISSUE TITLE
Bumping of version number based around `VERSION`, `MINOR` etc.

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#6]
Currently the version specifier tags `${{ fair.VERSION }}` etc are not implemented as they require access to the registry for bumping version numbers.

**Comment by soniamitchell** [comment]
Hopefully this isn't out of context, but FYI, `${{ fair.VERSION }}` is not one of the listed variables in the config. In addition, variable names handled by the CLI are prepended `CLI.*`, not `fair.*`.

**Comment by richardreeve** [comment]
Variable names are no longer prepended by anything, and the description of what happens around versions is given [here](https://fairdatapipeline.github.io/docs/interface/config/#simple-inputs-and-outputs).

**Comment by DennisReddyhoff** [comment]
Examples:

User yaml:
```yaml
read:
- data_product: disease/SARS-CoV-2/*
```
Working yaml:
```yaml
run_metadata:
  namespace: dreddyhoff
read:
- data_product: disease/SARS-CoV-2/half-life
  use:
    version: 1.0.3
- data_product: disease/SARS-CoV-2/ifnectious-period
  use:
    version: 0.3.2
```

User yaml:
```yaml
run_metadata:
  version: ${{PATCH}}
write:
- data_product: my_output/*
- data_product: other_stuff/*
  use:
    namespace: someoneelse
    version: 1.0
```

Working yaml:
```yaml
run_metadata:
  namespace: dreddyhoff
write:
- data_product: my_output/time-series
  use:
    version: 0.3.2
- data_product: my_output/final-output
  use:
    version: 0.4.1
- data_product: my_output/*
  use:
    version: 0.0.1
- data_product: other_stuff/*
  use:
    namespace: someoneelse
    version: 1.0
```
