### ISSUE TITLE
Ensure namespace is matched during register substitution and filters are applied to globbing

### ISSUE THREAD

**Issue by kzscisoft** [FAIRDataPipeline/FAIR-CLI#62]
- [x] Currently the `namespace` is not applied for `register` during `fair run`, this needs to be read into the result retrieval.
- [x] During globbing if there is a `use` statement with the glob expression then this needs to also be applied.
- [x] Replacement of `data_product` under `use` with `name` to match filters? This would be the simplest way to fix the issue of the two not matching.

E.g.
```yaml
read:
    data_product: my_data/a_product/*
    use:
        namespace: EERA
````
