### ISSUE TITLE
CI mode needs tweaking / `write_data_store` should be taken from `cli-config.yaml` if missing...

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#64]
At the moment, I can run:
```sh
fair init --ci
fair pull register.yaml
fair run --ci register.yaml
```
But to do that I need to edit `register.yaml` to say what the `write_data_store` should be, which I have to take from the global `cli-config.yaml` file or copy out of a dummy `fair create ci.yaml` script I create. Everything else is stable.

In fact, we should not have to put the `write_data_store` into a user config - it should just be taken from the global `~/.fair/cli` config file if missing. That way the yaml files can be stable over runs.

**Comment by kzscisoft** [comment]
@richardreeve I think if and when the GitHub action works completely this `--ci` mode for `fair init` will no longer be necessary. I am already in `v2` of the action allowing the user to specify a few more options within the action itself. That said, I am surprised to see `write_data_store` not appearing, when I run `fair init --ci` it is indeed there. Because it is a CI runner and not a user space what is different though is that it will use a temporary directory instead:

```sh
fair init --ci
fair create
```

```yaml
run_metadata:
  local_data_registry_url: http://localhost:8000/api/
  remote_data_registry_url: http://localhost:8001/api/
  write_data_store: /tmp/tmp4ra37_1t/data_store
  local_repo: /home/kristian/Documents/SCRC/FAIR-CLI
  remote_repo: null
  default_input_namespace: testing
  default_output_namespace: testing
  description: Project description
 ```
 One change I have just made is to remove there being a `script` entry by default.
