### ISSUE TITLE
Allow registration of authors

### ISSUE THREAD

**Issue by richardreeve** [FAIRDataPipeline/FAIR-CLI#96]
At the moment you can't register authors, and you can't add them to an external object to say who created it.

**Comment by kzscisoft** [comment]
How is the author specified within a `config.yaml` for an `external_object`?
Is there a particular pseudo-code way you would like to be able to do this?

**Comment by richardreeve** [comment]
We don't have a standard for this at the moment. Do you have a thought? I was imagining it would be like a namespace. So something like:
```yaml
register:
  author: me
    
```

**Comment by kzscisoft** [comment]
Perhaps like namespace registration we should have author registration separate to use:
```yaml
register:
    - author: Kristian Zarebski
      identifier: <ORCID>
    - author: Richard Reeve
    # No ID = UUID used
```
